#!/usr/bin/env php
<?php

    include_once('config.php');

    ini:

    $now = time();

    $auth = base64_encode("$username:$password");
    $context = stream_context_create([
	"http" => [
	    "header" => "Authorization: Basic $auth"
	]
    ]);
    $notifications = json_decode(file_get_contents($server, false, $context));

    foreach($notifications as $notification)
    {
	//priority
	switch($notification->priority)
	{
	    case 4:
		    $face = 'face-angry';
		    break;
	    case 3:
		    $face = 'face-surprise';
		    break;
	    case 2:
		    $face = 'face-uncertain';
		    break;
	    case 1:
		    $face = 'face-glasses';
		    break;
	    case 0:
	    default:
		    $face = 'face-cool';
		    break;
	}

	if($notification->type == 'intermittent_power' && $notification->timestamp > $now-$time)
	{
	    

	    if($debug) print_r($notification);
	    system('notify-send -i '.$face.' "Alerta intermitencia dispositivo '.escapeshellarg($notification->data->device).'"');
	    sleep($time);
	    if($debug)echo "READY\n";
	}
    }

    goto ini;
?>